# Generated by Django 5.0.6 on 2024-06-18 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField()),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.avatar')),
            ],
            options={
                'db_table': 'users',
                'db_table_comment': 'User information',
            },
        ),
    ]
