# Generated by Django 5.0.6 on 2024-07-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('avatar_link', models.URLField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'db_table_comment': 'User information',
            },
        ),
    ]
