# Generated by Django 5.1 on 2024-10-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0002_match'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
