# Generated by Django 5.1 on 2024-11-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transcendence",
            "0002_profile_is_online_profile_last_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="profile_images/default.png",
                upload_to="profile_images",
            ),
        ),
    ]
