# Generated by Django 5.1 on 2024-10-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0004_remove_profile_avatar_remove_profile_avatar_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
