# Generated by Django 5.1 on 2024-08-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='User',
            new_name='user',
        ),
    ]
