from django.contrib import admin
from django.conf import settings
from django.urls import path

from . import views
from .providers import fortytwo

urlpatterns = [
    path(
        "",
        views.HomepageView.as_view(),
        name="home",
    ),
    path(
        "user/",
        views.ProfileView.as_view(),
        name="profile",
    ),
    path(
        "user/login/",
        views.LoginView.as_view(),
        name="login",
    ),
    path(
        "user/logout/",
        views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "user/signup/",
        views.SignupView.as_view(),
        name="signup",
    ),
    path(
        "user/password/change/",
        views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "user/password/change/done/",
        views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "user/password/reset/",
        views.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "user/password/reset/done/",
        views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "user/password/reset/<uid64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "user/password/reset/complete/",
        views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path(
        "user/stats/", 
        views.StatsView.as_view(), 
        name="stats"
        ),
    path(
        "user/friends/", 
        views.FriendsView.as_view(), 
        name="friends"
    ),
    path(
        "users/<str:username>/",
        views.ProfileOtherView.as_view(),
    ),
    # try make dynamic: user/oauth/<str:provider>/callback
    path(
        "oauth/callback/",
        fortytwo.do_provider_login,
        name="oauth_callback",
    ),
    path(
        "pong/",
        views.PongView.as_view(),
        name="pong",
    ),
    path(
        "pong/<str:mode>/",
        views.PongView.as_view(),
        name="pong",
    ),
    path(
        "pong/<str:mode>/play/",
        views.PongPlayView.as_view(),
        name="play",
    ),
    path(
        'match/', 
        views.save_match, 
        name='save_match'
    ),
    path(
        "tournament/",
        views.TournamentView.as_view(),
        name="tournament",
    ),
    path(
        "tournament/register",
        views.TournamentRegisterView.as_view(),
        name="tournament_register",
    ),
    path(
        "tournament/tournament_order/",
        views.TournamentOrderView.as_view(),
        name="tournament_order",
    ),
    path(
        "admin/",
        admin.site.urls,
    ),
]

# handle404...
