input {
  tcp {
    port => 5000  # Port for Logstash to listen for incoming logs
    codec => line { }  # Assuming your logs are in plain text
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "logstash-%{+YYYY.MM.dd}"  # Index name for daily logs
  }
}