
input {
  stdin { }  # Read from standard input for testing
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }  # Output to console for debugging
}
